**Code untuk matrix invers**

In [21]:
# Example 2_13 halaman 85 
import numpy as np
from LUpivot import *

def matInv(a):
    n = len(a[0])
    aInv = np.identity(n)
    a,seq = LUdecomp(a)
    for i in range(n):
        aInv[:,i] = LUsolve(a,aInv[:,i],seq)
    return aInv

a = np.array([[ 0.6, -0.4, 1.0],\
              [-0.3, 0.2, 0.5],\
              [ 0.6, -1.0, 0.5]])
aOrig = a.copy() # Save original [a]
aInv = matInv(a) # Invert [a] (original [a] is destroyed)
print("\naInv =\n",aInv)
print("\nCheck: a*aInv =\n", np.dot(aOrig,aInv))


aInv =
 [[ 1.66666667 -2.22222222 -1.11111111]
 [ 1.25       -0.83333333 -1.66666667]
 [ 0.5         1.          0.        ]]

Check: a*aInv =
 [[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00 -3.33066907e-16  1.00000000e+00]]


In [22]:
# Example 2_14 halaman 86
import numpy as np
from LUdecomp3 import *
n=6

#input matrix
d = np.ones((n))*2.0
d[n-1] = 5.0
# d = np.array([2.0,2.0,2.0,2.0,2.0,5.0])
e = np.ones((n-1))*(-1.0)
c = e.copy()

#Code untuk invers
aInv = np.identity(n)
c,d,e = LUdecomp3(c,d,e)
for i in range(n):
    aInv[:,i] = LUsolve3(c,d,e,aInv[:,i])
print("\nThe inverse matrix is:\n",aInv)


The inverse matrix is:
 [[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


**Code untuk Gauss Sidel**

In [65]:
# Exampl3 2_17 halaman 95
# Run the program with n = 20
# x[n-1] = omega*(1.0 - x[0] + x[n-2])/2.0 \
#             + (1.0 - omega)*x[n-1]

import numpy as np
from gaussSeidel import *

def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(x[1] - x[n-1])/2.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(x[i-1] + x[i+1])/2.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(1.0 - x[0] + x[n-2])/2.0 \
            + (1.0 - omega)*x[n-1]
    return x

n = eval(input("Number of equations ==> "))
x = np.zeros(n) #Apakah semuanya sama seperti ini? 
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

Number of equations ==> 20

Number of iterations = 259

Relaxation factor = 1.7054523107131407

The solution is:
 [-4.50000000e+00 -4.00000000e+00 -3.50000000e+00 -3.00000000e+00
 -2.50000000e+00 -2.00000000e+00 -1.50000000e+00 -9.99999997e-01
 -4.99999998e-01  2.14046747e-09  5.00000002e-01  1.00000000e+00
  1.50000000e+00  2.00000000e+00  2.50000000e+00  3.00000000e+00
  3.50000000e+00  4.00000000e+00  4.50000000e+00  5.00000000e+00]


In [3]:
# Exampl3 2_17 halaman 95
# Run the program with n = 20
# x[n-1] = omega*(1.0 - x[0] - x[n-2])/2.0 \
#             + (1.0 - omega)*x[n-1]
import numpy as np
from gaussSeidel import *
def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(x[1] - x[n-1])/2.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(x[i-1] + x[i+1])/2.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(1.0 - x[0] - x[n-2])/2.0 \
            + (1.0 - omega)*x[n-1]
    return x
n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

In [1]:
# Konjugat Gradien
# Example 2_18 halaman 97
# Run the program with n = 20
import numpy as np
from conjGrad import *

def Ax(v):
    n = len(v)
    Ax = np.zeros(n)
    Ax[0] = 2.0*v[0] - v[1]+v[n-1]
    Ax[1:n-1] = -v[0:n-2] + 2.0*v[1:n-1] -v[2:n]
    Ax[n-1] = -v[n-2] + 2.0*v[n-1] + v[0]
    return Ax

n = eval(input("Number of equations ==> "))
b = np.zeros(n)
b[n-1] = 1.0
x = np.zeros(n)
x,numIter = conjGrad(Ax,x,b)
print("\nThe solution is:\n",x)
print("\nNumber of iterations =",numIter)

Number of equations ==> 20

The solution is:
 [-4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5  5. ]

Number of iterations = 9


In [33]:
# Soal nomor 17 hlm 100
import numpy as np
from gaussSeidel import *
def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(x[1] - x[n-1])/4.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(x[i-1] + x[i+1])/4.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(100.0 - x[0] - x[n-2])/4.0 \
            + (1.0 - omega)*x[n-1]
    return x
n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

Number of equations ==> 20

Number of iterations = 20

Relaxation factor = 1.0963210904923082

The solution is:
 [-6.69872981e+00 -1.79491924e+00 -4.80947157e-01 -1.28869386e-01
 -3.45303867e-02 -9.25216104e-03 -2.47825742e-03 -6.60868644e-04
 -1.65217160e-04  3.74899724e-13  1.65217162e-04  6.60868645e-04
  2.47825742e-03  9.25216104e-03  3.45303867e-02  1.28869386e-01
  4.80947157e-01  1.79491924e+00  6.69872981e+00  2.50000000e+01]


In [15]:
# Soal nomor 16 hlm 100
# ada salah di bagian perumusan x[0], x[i] dan x[n-1]
import numpy as np
from gaussSeidel import *
def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(10 + 2*x[1] - x[2] - x[n-1])/3.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(-8 + x[i-2] + 2*x[i+1] - x[i+2])/3.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(10.0 - x[0] - x[3] - 2*x[n-2])/3.0 \
            + (1.0 - omega)*x[n-1]
    return x
n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

Number of equations ==> 6


IndexError: index 6 is out of bounds for axis 0 with size 6

In [7]:
# Soal Nomor 13 hlm 100
# Number of equation = 4 karena matrix nya orde 4
# Harusnya omega = 1.1 dan bi/Aii sesuai note yg ada di soal, pasti hasilnya lebih akurat
import numpy as np
from gaussSeidel import *
def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(15 + x[1])/4.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(10 + x[i-1] + x[i+1])/4.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(10.0 + x[n-2])/4.0 \
            + (1.0 - omega)*x[n-1]
    return x
n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

Number of equations ==> 4

Number of iterations = 14

Relaxation factor = 1.044640519135955

The solution is:
 [4.97607655 4.90430622 4.64114833 3.66028708]


In [6]:
# Pembuktian soal nomor 13 hlm 100 pake LUdecomp3
import numpy as np
from LUdecomp3 import *
c = np.ones((3))*(-1.0)
d = np.array([4.0,4.0,4.0,3.0])
e = c.copy()
b = np.array([15.0, 10.0, 10.0, 10.0])
c,d,e = LUdecomp3(c,d,e)
x = LUsolve3(c,d,e,b)
print('Hasil perhitungan menggunakan LUdecomp3')
print("x =\n",x)

Hasil perhitungan menggunakan LUdecomp3
x =
 [5. 5. 5. 5.]


In [8]:
# Example 2.15 hlm 92
# Gauss seidel tanpa relaksasi
# Number of equation = 3 karena matrix nya 3
import numpy as np
from seidel import *
def iterEqs(x):
    n = len(x)
    x[0] = (12.0 + x[1] - x[n-1])/4.0 
    for i in range(1,n-1):
        x[1] = (-1.0 + x[0] + 2*x[n-1])/4.0
    x[n-1] = (5.0 - x[0] + 2*x[1])/4.0 
    
    return x
n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter = seidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
# print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)

Number of equations ==> 3

Number of iterations = 14

The solution is:
 [3. 1. 1.]


In [4]:
# Konjugat Gradien
# Example 2_18 halaman 97
# Run the program with n = 20
import numpy as np
from conjGrad import *

def Ax(v):
    n = len(v)
    Ax = np.zeros(n)
    Ax[0] = 200.0*v[0] - 50*v[1]
    Ax[1:n-1] = 50*v[0:n-2] + -125.0*v[1:n-1] + 75.0*v[2:n]
    Ax[n-1] = -225*v[n-2] + 225.0*v[n-1] 
    return Ax

n = eval(input("Number of equations ==> "))
b = np.zeros(n)
b[n-1] = 1.0
x = np.zeros(n)
x,numIter = conjGrad(Ax,x,b)
print("\nThe solution is:\n",x)
print("\nNumber of iterations =",numIter)

Number of equations ==> 4

The solution is:
 [ 3.62553154e-05  9.75098015e-03  3.18655876e-01 -1.43575048e-01]

Number of iterations = 3
