In [27]:
import numpy as np 
a = [[2.0,1.0,-1.0],[-3.0,-1.0,2.0],[-2.0,1.0,2.0]]
b = [[8.0],[-11.0],[-3.0]]

a = np.array(a)
b = np.array(b)

lam = a[1][0]/a[0][0]
a[1][0:3] = a[1][0:3] - lam*a[0][0:3]
b[1] = b[1] - lam*b[0]

lam = a[2][0]/a[0][0]
a[2][0:3] = a[2][0:3] - lam*a[0][0:3]
b[2] = b[2] - lam*b[0]

lam = a[2][1]/a[1][1]
a[2][1:3] = a[2][1:3] - lam*a[1][1:3]
b[2] = b[2] - lam*b[1]


print(a)
print(b)

[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
[[8.]
 [1.]
 [1.]]


In [19]:
import numpy as np 
a = [[2.0,1.0,-1.0],[-3.0,-1.0,2.0],[-2.0,1.0,2.0]]
b = [[8.0],[-11.0],[-3.0]]

a = np.array(a)
b = np.array(b)

# eliminasi phase
for k in range(0,2):
    for i in range(k+1,3):
        lam = a[i][k]/a[k][k]
        a[i][k:3] = a[i][k:3] - lam*a[k][k:3]
        b[i] = b[i] - lam*b[k]
print(a)
print(b)
    

[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
[[8.]
 [1.]
 [1.]]


In [33]:
a = [[2.0,1.0,-1.0],[-3.0,-1.0,2.0],[-2.0,1.0,2.0]]
b = [[8.0],[-11.0],[-3.0]]

a = np.array(a)
b = np.array(b)

def gaussElimin(a,b):
    n = len(a)
    for k in range(0,2):
        for i in range(k+1,3):
            lam = a[i][k]/a[k][k]
            a[i][k:3] = a[i][k:3] - lam*a[k][k:3]
            b[i] = b[i] - lam*b[k]
    for k in range(n-1,-1,-1):
        sumtemp = 0
        for j in range(k+1,n):
            sumtemp += a[k][j]*b[j]
        b[k] = (b[k] - sumtemp)/a[k][k]
    return b

print(gaussElimin(a,b))

#Atau rumus nya dapat dituliskan sbb:
# def gaussElimin(a,b):
#     n = len(b)
#     # Eliminasi fase
#     for k in range(0,n-1):
#         for i in range(k+1,n):
#             if a[i,k] != 0.0:
#                 lam = a [i,k]/a[k,k]
#                 a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
#                 b[i] = b[i] - lam*b[k]
#     # Back substitution
#     for k in range(n-1,-1,-1):
#         b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
#     return b
# print(gaussElimin(a,b))

[[ 2.]
 [ 3.]
 [-1.]]


In [28]:
#Masih perlu koreksi
A = np.array([[6,-4,1],[-4,6,-4],[1,-4,6]])
B1 = np.array([[-14],[36],[6]])
B2 = np.array ([[22],[-18],[7]])

print(A)
print(B1)
print(B2)

X1 = gaussElimin(A,B1)
X2 = gaussElimin(A,B2)

print(X1)
print(X2)

[[ 6 -4  1]
 [-4  6 -4]
 [ 1 -4  6]]
[[-14]
 [ 36]
 [  6]]
[[ 22]
 [-18]
 [  7]]
[[11]
 [25]
 [17]]
[[ 1]
 [-3]
 [ 3]]
