In [1]:
import numpy as np
from gaussElimin import *

a = np.array([[2.0,-3.0,-1.0],[3.0,2.0,-5.0],[2.0,4.0,-1.0]])
b = np.array([3.0,-9.0,-5.0])

A = gaussElimin(a,b)
print('x=\n', A)

x=
 [ 0.65306122 -1.14285714  1.73469388]


In [1]:
import numpy as np
from LU import *

a = np.array([[200.0,-50.0,0.0,0.0],[50.0,-125.0,75.0,0.0],[0.0,75.0,-300.0,225.0]])
b = np.array([0.0,0.0,0.0,200.0])

a = LUdecomp(a)
b = LUsolve(a,b)

print('x=\n', b)

x=
 [  0.  -0.  -0. 200.]


In [3]:
import numpy as np
from LUdecomp3 import *
c = np.ones((4))*(-1.0)
d = np.ones((5))*2.0
e = c.copy()
b = np.array([5.0, -5.0, 4.0, -5.0, 5.0])
c,d,e = LUdecomp3(c,d,e)
x = LUsolve3(c,d,e,b)
print('Hasil perhitungan menggunakan LUdecomp3')
print("x =\n",x)

Hasil perhitungan menggunakan LUdecomp3
x =
 [ 2. -1.  1. -1.  2.]


In [8]:
import numpy as np
from LUdecomp5 import *
d = np.ones((4))*(-1.0)
e = np.array([2.0,4.0,4.0,2.0,3.0])
f = d.copy()
b = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
d,e,f = LUdecomp5(d,e,f)
x = LUsolve5(d,e,f,b)
# print(d,e,f)
print('Hasil perhitungan menggunakan LUdecomp5')
print("x =\n",x)

Hasil perhitungan menggunakan LUdecomp5
x =
 [-1.   0.6  1.2  0.2  5. ]


In [23]:
# Gauss Pivot halaman 73
# Modul error masih belum ditemukan
import numpy as np
import swap
# import error

a = np.array([[2.0,-2.0,6.0],[-2.0,4.0,3.0],[-1.0,8.0,4.0]])
b = np.array([16.0,0.0,-1.0])

# def gaussPivot(a,b,tol=1.0e-12)
def gaussPivot(a,b):
    n = len(b)
    
    # Set up scale factors
    s = np.zeros(n)
    for i in range(n):
        s[i] = max(np.abs(a[i,:]))
    for k in range(0,n-1):

    # Row interchange, if needed
        p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k
#         if abs(a[p,k]) < tol: error.err('Matrix is singular')
        if p != k:
            swap.swapRows(b,k,p)
            swap.swapRows(s,k,p)
            swap.swapRows(a,k,p)
            
    # Elimination
    for i in range(k+1,n):
        if a[i,k] != 0.0:
            lam = a[i,k]/a[k,k]
            a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
            b[i] = b[i] - lam*b[k]
#     if abs(a[n-1,n-1]) < tol: error.err('Matrix is singular')

    # Back substitution
    b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

print('Hasil perhitungan Gauss-Pivot:')
print(gaussPivot(a,b))

Hasil perhitungan Gauss-Pivot:
[ 0.875 -1.25   2.25 ]


In [33]:
import numpy as np
import swap
# import error

a = np.array([[2.0,-2.0,6.0],[-2.0,4.0,3.0],[-1.0,8.0,4.0]])
b = np.array([16.0,0.0,-1.0])

# def LUdecomp(a,tol=1.0e-9):
def LUdecomp(a):
    n = len(a)
    seq = np.array(range(n))

    # Set up scale factors
    s = np.zeros((n))
    for i in range(n):
        s[i] = max(abs(a[i,:]))
    
    for k in range(0,n-1):
    
        # Row interchange, if needed
        p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k
#         if abs(a[p,k]) < tol: error.err('Matrix is singular')
        if p != k:
            swap.swapRows(s,k,p)
            swap.swapRows(a,k,p)
            swap.swapRows(seq,k,p)

        # Elimination
    for i in range(k+1,n):
        if a[i,k] != 0.0:
            lam = a[i,k]/a[k,k]
            a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
            a[i,k] = lam
    return a,seq

def LUsolve(a,b,seq):
    n = len(a)
    
    # Rearrange constant vector; store it in [x]
    x = b.copy()
    for i in range(n):
        x[i] = b[seq[i]]

    # Solution
    for k in range(1,n):
        x[k] = x[k] - np.dot(a[k,0:k],x[0:k])
    x[n-1] = x[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        x[k] = (x[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    return x

print('Hasil perhitungan LUdecomp:')
print(LUdecomp(a))
# print(LUsolve(a,b,....))

Hasil perhitungan LUdecomp:
(array([[-2.  ,  4.  ,  3.  ],
       [-1.  ,  8.  ,  4.  ],
       [ 2.  , -0.25,  7.  ]]), array([1, 2, 0]))
[-6.07142857  4.07142857 -4.14285714]
