# Dhoni Ikhsan Widodo

In [1]:
#Import modul yang kita butuhkan untuk menghitung; penjumlahan, perkalian dan determinan matrix
from numpy.linalg import *
from numpy import *

#Fungsi untuk menginput matrix, lalu memunculkan hasil inputnya
def input_matrix(dim):
    print("Masukkan nilai matrix :")
    A = []
    for i in range (0,dim):
        baris = []
        for j in range(0,dim):
            string = input('A['+str(i+1)+']['+str(j+1)+']: ')
            baris.append(eval(string))
        A.append(baris)

    a = array(A)
    print(" ") 
    print("Matrix yang di input :")
    print(a)
    return a

In [2]:
print("Hasil penjumlahan matrix orde 2: ")
input_matrix(2) + input_matrix(2)

Hasil penjumlahan matrix orde 2: 
Masukkan nilai matrix :
A[1][1]: 1
A[1][2]: 2
A[2][1]: 3
A[2][2]: 4
 
Matrix yang di input :
[[1 2]
 [3 4]]
Masukkan nilai matrix :
A[1][1]: 4
A[1][2]: 3
A[2][1]: 2
A[2][2]: 1
 
Matrix yang di input :
[[4 3]
 [2 1]]


array([[5, 5],
       [5, 5]])

In [3]:
print("Hasil penjumlahan matrix orde 3: ")
input_matrix(3) + input_matrix(3)

Hasil penjumlahan matrix orde 3: 
Masukkan nilai matrix :
A[1][1]: 1
A[1][2]: 2
A[1][3]: 3
A[2][1]: 4
A[2][2]: 5
A[2][3]: 6
A[3][1]: 7
A[3][2]: 8
A[3][3]: 9
 
Matrix yang di input :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Masukkan nilai matrix :
A[1][1]: 9
A[1][2]: 8
A[1][3]: 7
A[2][1]: 6
A[2][2]: 5
A[2][3]: 4
A[3][1]: 3
A[3][2]: 2
A[3][3]: 1
 
Matrix yang di input :
[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [4]:
print("Hasil perkalian matrix orde 2: ")
input_matrix(2).dot(input_matrix(2)) #Mencari hasil perkalian berdasarkan matrix yang di input, dengan dimensi matrix yaitu 2

Hasil perkalian matrix orde 2: 
Masukkan nilai matrix :
A[1][1]: 1
A[1][2]: 1
A[2][1]: 1
A[2][2]: 1
 
Matrix yang di input :
[[1 1]
 [1 1]]
Masukkan nilai matrix :
A[1][1]: 2
A[1][2]: 2
A[2][1]: 2
A[2][2]: 2
 
Matrix yang di input :
[[2 2]
 [2 2]]


array([[4, 4],
       [4, 4]])

In [5]:
print("Hasil perkalian matrix orde 3: ")
input_matrix(3).dot(input_matrix(3)) #Mencari hasil perkalian berdasarkan matrix yang di input, dengan dimensi matrix yaitu 3

Hasil perkalian matrix orde 3: 
Masukkan nilai matrix :
A[1][1]: 1
A[1][2]: 2
A[1][3]: 3
A[2][1]: 4
A[2][2]: 5
A[2][3]: 6
A[3][1]: 7
A[3][2]: 8
A[3][3]: 9
 
Matrix yang di input :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Masukkan nilai matrix :
A[1][1]: 9
A[1][2]: 8
A[1][3]: 7
A[2][1]: 6
A[2][2]: 5
A[2][3]: 4
A[3][1]: 3
A[3][2]: 2
A[3][3]: 1
 
Matrix yang di input :
[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [6]:
#Membuat fungsi untuk mencari nilai determinan
def determinan_matrix(len):
    B = []
    for i in range (0,len):
        simpan = []
        for j in range(0,len):
            mulai = input('['+str(i+1)+']['+str(j+1)+']: ')
            simpan.append(eval(mulai))
        B.append(simpan)
    b = array(B)
    print(" ")
    print("Matrix yang di input : ")
    print (b)
    print(" ")
    print("Nilai determinan yang didapat yaitu: ")
    return b

In [8]:
print("Hasil detrminan matrix orde 2: ")
round(det(determinan_matrix(2))) 

Hasil detrminan matrix orde 2: 
[1][1]: 1
[1][2]: 2
[2][1]: 3
[2][2]: 4
 
Matrix yang di input : 
[[1 2]
 [3 4]]
 
Nilai determinan yang didapat yaitu: 


-2.0

In [9]:
print("Hasil detrminan matrix orde 3: ")
round(det(determinan_matrix(3))) 

Hasil detrminan matrix orde 3: 
[1][1]: 1
[1][2]: 2
[1][3]: 3
[2][1]: 4
[2][2]: 5
[2][3]: 6
[3][1]: 7
[3][2]: 8
[3][3]: 9
 
Matrix yang di input : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Nilai determinan yang didapat yaitu: 


0.0

Semua fungsi yang sudah dibuat dapat dipergunakan untuk operasi matrix (penjumlahan, pengurangan, perkalian) dan mencari nilai determinan dengan cara memanggil kembali fungsi tersebut, lalu memasukkan nilai matrix nya.
Fungsi tersebut dapat menghitung mulai dari matrix dimensi 2 sampai berapapun.
Angka yang di input diatas hanya berupa contoh soal sederhana yang bertujuan untuk membuktikan bahwa code diatas adalah benar dengan hasil perhitungan yang sesungguhnya, namun masih perlu evaluasi terhadap interface yang baik agar tidak terjadi kesalahan pada saat input matrixnya.

TTD

Dhoni Ikhsan Widodo